HTTP. Работа с сервером
htmlacademy-vue/1237807-pizza-1 pull request #5
Opened 2022-02-11 11:16 UTC by julia-marta

2022-02-11 20:14 UTC, pisarevamarina requested changes
Хорошая работа, апи модули подключены, тестовые данные заменены на данные с сервера, приложение отрабатывает нужный функционал) 
есть небольшие комментарии по улучшению работы, так же, прошу поправить ошибки в консоли при оформлении заказа и перехода на страницу выполненных заказов (сейчас выполненные заказы не появляются после оформления)

2022-02-11 20:14 UTC, pisarevamarina commented on src/frontend/src/layouts/AppLayoutDefault.vue
> +      :show-login="!isAuthenticated && $route.name !== 'Login'"
я бы предложила не передавать эти значения пропсами. будет лучше чтобы компонент хедера сам управлял своим состоянием, а лэяут глупо рендерил компоненты которые в нем есть.

2022-02-11 20:14 UTC, pisarevamarina commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +    ...mapState(["Auth"]),
мы ведь здесь тоже используем Auth из стора, будет логичней в самом компоненте  управлять состоянием.

2022-02-11 20:14 UTC, pisarevamarina commented on src/frontend/src/modules/cart/components/CartFooter.vue
> +      <Button type="submit" :disabled="disabled" @click.prevent="submit">
после того как пользователь нажал на кнопку оформить заказ и появился попап с сообщением об успехе - кнопку лучше сделать неактивной, обнуляя текущий заказ. сейчас я могу нажать кнопку после оформления заказа неограниченное количество раз, в консоли появляется ошибка

2022-02-11 20:14 UTC, pisarevamarina commented on src/frontend/src/modules/cart/components/CartDeliveryForm.vue
> +          v-model="Cart.deliveryOption"
текущий реализация не совсем корректна. мы не можем менять Стейт напрямую, для этого мы используем мутации.здесь лучше передавать value.  есть два варианта реализации
1. оставить v-model, но использовать computed-свойство с get и set
2. обновлять выбранное  значение на событие change +  передавать value уже обновленное из стейта.

2022-02-11 20:14 UTC, pisarevamarina commented on src/frontend/src/modules/cart/components/CartDeliveryForm.vue
> +        v-model="Cart.phone"
аналогично, мутирование стейта напрямую

2022-02-14 21:48 UTC, julia-marta commented
Поправила ещё пару найденных багов:
- исправлена ошибка при редактировании адреса, если комментарий в адресе равен null (когда адрес добавляется автоматически после оформления заказа)
- исправлена ошибка при отрисовке заказов, когда в заказе отсутствуют пиццы (только доп. товары)

2022-02-15 07:51 UTC, pisarevamarina approved these changes
все замечания поправлены, функционал соответствует тз 👍🏻 работа принимается, желаю успехов в дальнейшем обучении :)

2022-02-15 07:51 UTC, pisarevamarina commented on src/frontend/src/layouts/AppLayoutHeader.vue
> +      return this.Auth.isAuthenticated;
отлично! теперь компонент независимо управляет своим состоянием :)

2022-02-15 07:51 UTC, merged